import Head from 'next/head';
import React from 'react';
import { Navbar } from '../components/Navbar';

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main>
        <h1>Hello world</h1>
      </main>
    </div>
  );
};

export default Home;
